### ISSUE TITLE
remove python output from database build notebook 

### ISSUE THREAD

**Issue by LisaHopcroft** [opensafely/database-notebooks#36]
The content of the Python cells is being included in the output html for [the database build notebook](https://reports.opensafely.org/reports/opensafely-tpp-database-builds/). @rebkwok has suggested that this _may_ be due to a change to `nbconvert` (requiring the use of the `--no-input` flag).

**Comment by wjchulme** [comment]
This was ultimately due to a change in the release process (discussed [here on slack](https://bennettoxford.slack.com/archives/C31D62X5X/p1669973717289519?thread_ts=1669972467.643339&cid=C31D62X5X)). @rebkwok has helpfully shown me how remove code chunks within this new release process. I may document, but the repo will [soon be superceded by a replacement using sql-runner](https://github.com/opensafely-core/sqlrunner/issues/20).
